### ISSUE TITLE
how to use this mylinux?  is it working?

### ISSUE THREAD

**Issue by iswardasa** [urosjarc/mylinux#10]

**Comment by urosjarc** [comment]
Its still in active development. I don't know how much sense it would be to continue this project since so many tools is on the web, besides I kinda don't have time. :-1:

**Comment by iswardasa** [comment]
oh, ok.  i see.  i was simply curious because i am looking to make very specific linux redistributables.  i have noticed there are some tools out there, but have not gotten too far in my research or even development yet to need them.  thank you for your response.

**Comment by urosjarc** [comment]
Well `mylinux` application will be developed someday, in the mean time I can show you my distribution of linux. If you have something special in mind I can help you with some meaningfull suggestion since I know linux world quite well.

This is my linux distribution: https://github.com/urosjarc/mylinux/wiki/Ubuntu-install

**Comment by iswardasa** [comment]
okay.  i will check that distribution out !

wow.  thats really cool.  those commands look very simple, yet powerful.

There is infact something unique that i have in mind.  i developing with a particularly specific use of linux in mind.  i have made one iteration of the distribution before using stright debian linux, but then found out that the wifi and video drivers were a pain to get working.  now i develop using lubuntu as my os.  lubutu (ubuntu) solves the drivers problem pretty well.

i havn't quite produced the second iteration of my distribution yet though.

what i have in mind is basically a very stripped down ubuntu to start with.  very minimal.  i would like to disable all of the hotkeys.  basically, this would be a kiosk style distribution that would simply boot up my java program in full-screen mode upon loading, then shutdown the computer as soon as the java  program exits.  

thusfar, i am going with a java program as the core of my software because of it's portability and it's impressive language syntax and extensive libraries.  I have not gotten very far in the java client part of the coding yet, as i have mostly been working on some java ee server classes.  i am not sure if the java platform will be sufficient to satisfy the end users.  it may be that i will include a couple of modified linux programs as well so that the end user has a fuller experience.

when i used the debian install, i simply made it load openbox.  openbox loaded a surf web browser that automatically navigeted to one website.  i disabled all of the hotkeys and menus and such, so the user was limited to this one website and the hyperlink navigation within this website.  upon closing the surf browser, the computer would shutdown.  i found this limiting environment to lend for very focused use of the computer without the possibilities of getting distracted.  i was amazed at how it felt nostalgic.  it was like being back in the 80's before devices used multitasking.

so i figure a stripped down ubuntu/lubuntu version would give the drivers needed for full hardware recognition, then i would simply lock it down to limit the functionality to a very narrow purpose.

**Comment by iswardasa** [comment]
btw, i like the idea of text base user interface on your "mylinux".

**Comment by urosjarc** [comment]
For my needs I started to creating my own debian dist base on debian server min image. And there was a lot of problem that I have to solve before everthing started to work like a butter. But since my needs changees all the time I joust could not find time to constantly changing configuration, installation settings. So I went with normal ubuntu distribution with custom window manager.

[i3 tiling window manager](http://i3wm.org/)

This is minimal desktop env for linux x11. Its fast as light and it provide a lot of customatization.

For limiting user functinality you have guest account and chmod at your disposal. But if you really want your custom installation check this out.

[how-to-customize-the-ubuntu-live-cd](http://askubuntu.com/questions/48535/how-to-customize-the-ubuntu-live-cd)
